package io.github.jf3env.architecture.bytecode;

import java.util.Set;

/** Stable identities of the executed context-first ArchUnit inventory. */
public final class BytecodeContracts {
  public BytecodeContracts() {}

  public Set<String> requiredRules() {
    return Set.of(
        "CLASSES_RESIDE_IN_CONTEXT_SHAPE",
        "CONTEXTS_ONLY_TALK_THROUGH_API",
        "CONTEXTS_ARE_FREE_OF_CYCLES",
        "LAYERS_POINT_INWARD",
        "DOMAIN_IS_FRAMEWORK_FREE",
        "API_IS_A_PUBLISHED_LANGUAGE",
        "INTEGRATION_EVENTS_ARE_PUBLIC_RECORDS",
        "PLATFORM_DEPENDS_ON_NO_CONTEXT",
        "TRANSACTIONS_BELONG_TO_APPLICATION",
        "PERSISTENCE_IS_THE_ONLY_JPA_USER",
        "REST_TALKS_ONLY_TO_APPLICATION",
        "OUTBOUND_DOES_NOT_DEPEND_ON_APPLICATION",
        "HANDLERS_DO_NOT_RETURN_AGGREGATES",
        "ONE_PRODUCER_PER_CONTEXT",
        "DOMAIN_REPOSITORIES_ARE_INTERFACES",
        "DOMAIN_PACKAGES_ARE_NULL_MARKED",
        "AGGREGATE_ROOTS_HAVE_PRIVATE_STATE",
        "AGGREGATE_ROOTS_HAVE_NO_PUBLIC_SETTERS",
        "DOMAIN_STATE_IS_PRIVATE",
        "ONLY_AGGREGATES_REASSIGN_DOMAIN_STATE",
        "DOMAIN_TYPES_ARE_CONSTRUCTED_BY_THEIR_DOMAIN",
        "TRANSFER_OBJECT_PACKAGES_CONTAIN_ONLY_TRANSFER_OBJECTS",
        "TRANSFER_OBJECTS_BELONG_TO_DTO_PACKAGES",
        "JPA_ENTITIES_FOLLOW_ENTITY_CONVENTIONS",
        "ENTITY_PACKAGES_CONTAIN_ONLY_ENTITIES",
        "REST_TRANSFER_OBJECTS_DO_NOT_LEAK_INNER_LAYERS",
        "ENTITY_REPRESENTATIONS_DO_NOT_LEAK_INNER_LAYERS",
        "MAPPERS_USE_MAPSTRUCT",
        "MAPSTRUCT_MAPPERS_HAVE_A_MAPPER_PACKAGE",
        "MAPSTRUCT_MAPPERS_ARE_INTERFACES",
        "MAPSTRUCT_MAPPERS_HAVE_GENERATED_IMPLEMENTATIONS",
        "MAPSTRUCT_MAPPER_METHODS_ARE_ABSTRACT",
        "BOUNDARY_CARRIERS_ARE_ONLY_CONSTRUCTED_BY_MAPSTRUCT",
        "BOUNDARY_CARRIER_SETTERS_ARE_ONLY_CALLED_BY_MAPSTRUCT",
        "BOUNDARY_CARRIER_STATE_IS_PRIVATE");
  }
}
