package io.github.jf3env.architecture.bytecode;

import java.util.Set;

/** Stable identities preserved from the original executed ArchUnit inventory. */
public final class BytecodeContracts {
  public BytecodeContracts() {}

  public Set<String> requiredRules() {
    return Set.of(
        "LAYER_COMMUNICATION",
        "CLASSES_ARE_GROUPED_BY_LAYER_AND_DOMAIN",
        "APPLICATION_LAYER_IS_ABSENT",
        "DOMAINS_ARE_FREE_OF_CYCLES",
        "SUBPACKAGES_DO_NOT_ACCESS_ANCESTOR_PACKAGES",
        "DOMAIN_ROOT_CLASSES_ARE_INTERFACES",
        "DOMAIN_SERVICES_RESIDE_IN_OWN_SERVICE_PACKAGES",
        "SERVICE_CAPABILITIES_DECLARE_TYPE_ROLES",
        "DOMAIN_COMPONENTS_FOLLOW_STRUCTURAL_OWNERS",
        "DOMAIN_INTERFACES_RESIDE_AT_THE_DOMAIN_ROOT",
        "DOMAIN_REPOSITORIES_ARE_INTERFACES",
        "ASSET_DOMAIN_PACKAGES_ARE_WORKSPACE_OWNED",
        "ASSET_CHANGING_SERVICES_USE_WORKSPACE_AUTHORITY",
        "WORKSPACE_ASSET_SERVICES_HAVE_NO_ASSET_PERSISTENCE_REPOSITORY",
        "REST_DOES_NOT_BYPASS_DOMAIN_SERVICES",
        "REST_DOES_NOT_ACCESS_ROOT_REPOSITORIES",
        "DOMAIN_SERVICES_ARE_CONSTRUCTED_BY_INFRASTRUCTURE",
        "PERSISTENCE_DOES_NOT_DEPEND_ON_DOMAIN_SERVICE_GATES",
        "TRANSACTION_ANNOTATIONS_BELONG_TO_PERSISTENCE",
        "DOMAIN_IS_FRAMEWORK_FREE",
        "DOMAIN_PACKAGES_ARE_NULL_MARKED",
        "DOMAIN_TYPES_ARE_NOT_RECORDS",
        "DOMAIN_TYPES_DECLARE_THEIR_ROLE",
        "DOMAIN_EXCEPTIONS_LIVE_IN_EXCEPTIONS_PACKAGES",
        "AGGREGATE_ROOTS_HAVE_PRIVATE_STATE",
        "AGGREGATE_ROOTS_HAVE_NO_PUBLIC_SETTERS",
        "DOMAIN_STATE_IS_PRIVATE",
        "ONLY_AGGREGATES_REASSIGN_DOMAIN_STATE",
        "DOMAIN_SERVICES_DO_NOT_EXPOSE_AGGREGATES",
        "TRANSFER_OBJECT_PACKAGES_CONTAIN_ONLY_TRANSFER_OBJECTS",
        "TRANSFER_OBJECTS_BELONG_TO_DTO_PACKAGES",
        "JPA_ENTITIES_FOLLOW_ENTITY_CONVENTIONS",
        "ENTITY_PACKAGES_CONTAIN_ONLY_ENTITIES",
        "REST_TRANSFER_OBJECTS_DO_NOT_LEAK_INNER_LAYERS",
        "ENTITY_REPRESENTATIONS_DO_NOT_LEAK_INNER_LAYERS",
        "MAPPERS_USE_MAPSTRUCT",
        "MAPSTRUCT_MAPPERS_HAVE_A_MAPPER_PACKAGE",
        "MAPSTRUCT_MAPPERS_ARE_INTERFACES",
        "MAPSTRUCT_MAPPERS_HAVE_GENERATED_IMPLEMENTATIONS",
        "BOUNDARY_CARRIERS_ARE_ONLY_CONSTRUCTED_BY_MAPSTRUCT",
        "BOUNDARY_CARRIER_SETTERS_ARE_ONLY_CALLED_BY_MAPSTRUCT",
        "BOUNDARY_CARRIER_STATE_IS_PRIVATE",
        "MAPSTRUCT_MAPPER_METHODS_ARE_ABSTRACT");
  }
}
