package io.github.jf3env.architecture.source;

import java.util.HashSet;
import java.util.Set;
import net.sourceforge.pmd.lang.java.ast.ASTAssignableExpr.ASTNamedReferenceExpr;
import net.sourceforge.pmd.lang.java.ast.ASTAssignmentExpression;
import net.sourceforge.pmd.lang.java.ast.ASTClassDeclaration;
import net.sourceforge.pmd.lang.java.ast.ASTConstructorDeclaration;
import net.sourceforge.pmd.lang.java.ast.ASTEmptyStatement;
import net.sourceforge.pmd.lang.java.ast.ASTExplicitConstructorInvocation;
import net.sourceforge.pmd.lang.java.ast.ASTExpressionStatement;
import net.sourceforge.pmd.lang.java.ast.ASTFieldAccess;
import net.sourceforge.pmd.lang.java.ast.ASTThisExpression;
import net.sourceforge.pmd.lang.java.ast.ASTVariableAccess;
import net.sourceforge.pmd.lang.java.rule.AbstractJavaRule;
import net.sourceforge.pmd.lang.java.symbols.JFieldSymbol;
import net.sourceforge.pmd.lang.java.symbols.JVariableSymbol;

/**
 * Checks handwritten source, so a Lombok annotation cannot disguise a manually implemented trivial
 * constructor.
 */
public final class LombokConstructorRule extends AbstractJavaRule {
  private static final Set<String> CONSTRUCTOR_ANNOTATIONS =
      Set.of(
          "lombok.NoArgsConstructor",
          "lombok.RequiredArgsConstructor",
          "lombok.AllArgsConstructor",
          "lombok.Data",
          "lombok.Value",
          "lombok.Builder",
          "lombok.experimental.SuperBuilder");

  public LombokConstructorRule() {
    setName("LombokSimpleConstructor");
    setLanguage(net.sourceforge.pmd.lang.java.JavaLanguageModule.getInstance());
    setMessage("Simple constructors must be generated by Lombok");
  }

  @Override
  public Object visit(ASTClassDeclaration type, Object context) {
    if (!type.isInterface()
        && type.getDeclarations(ASTConstructorDeclaration.class).isEmpty()
        && !type.isAnyAnnotationPresent(CONSTRUCTOR_ANNOTATIONS)) {
      asCtx(context)
          .addViolationNoSuppress(
              type,
              type.getAstInfo(),
              "{0}",
              "LOMBOK_SIMPLE_CONSTRUCTOR: "
                  + type.getBinaryName()
                  + " must declare a Lombok constructor annotation"
                  + " instead of relying on an implicit constructor");
    }
    return super.visit(type, context);
  }

  @Override
  public Object visit(ASTConstructorDeclaration constructor, Object context) {
    if (isSimple(constructor)) {
      asCtx(context)
          .addViolationNoSuppress(
              constructor,
              constructor.getAstInfo(),
              "{0}",
              "LOMBOK_SIMPLE_CONSTRUCTOR: "
                  + constructor.getName()
                  + " only initializes fields or is empty; use @NoArgsConstructor,"
                  + " @RequiredArgsConstructor or @AllArgsConstructor");
    }
    return super.visit(constructor, context);
  }

  private static boolean isSimple(ASTConstructorDeclaration constructor) {
    Set<JVariableSymbol> parameters = new HashSet<>();
    constructor
        .getFormalParameters()
        .forEach(parameter -> parameters.add(parameter.getVarId().getSymbol()));
    Set<JVariableSymbol> usedParameters = new HashSet<>();
    Set<JFieldSymbol> fields = new HashSet<>();
    for (var statement : constructor.getBody().children()) {
      if (statement instanceof ASTEmptyStatement) {
        continue;
      }
      if (statement instanceof ASTExplicitConstructorInvocation invocation
          && invocation.isSuper()
          && !invocation.isQualified()
          && invocation.getArgumentCount() == 0) {
        continue;
      }
      if (!(statement instanceof ASTExpressionStatement expression)
          || !(expression.getChild(0) instanceof ASTAssignmentExpression assignment)
          || assignment.isCompound()
          || !(assignment.getRightOperand() instanceof ASTVariableAccess parameter)
          || !parameters.contains(parameter.getReferencedSym())
          || !usedParameters.add(parameter.getReferencedSym())
          || !(assignment.getLeftOperand() instanceof ASTNamedReferenceExpr target)
          || !(target.getReferencedSym() instanceof JFieldSymbol field)
          || field.isStatic()
          || !field.getEnclosingClass().equals(constructor.getSymbol().getEnclosingClass())
          || !fields.add(field)
          || (target instanceof ASTFieldAccess access
              && !(access.getQualifier() instanceof ASTThisExpression))) {
        return false;
      }
    }
    return usedParameters.equals(parameters);
  }
}
