package io.github.jf3env.architecture.source;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import net.sourceforge.pmd.lang.java.JavaLanguageModule;
import net.sourceforge.pmd.lang.java.ast.ASTAssignableExpr.ASTNamedReferenceExpr;
import net.sourceforge.pmd.lang.java.ast.ASTAssignmentExpression;
import net.sourceforge.pmd.lang.java.ast.ASTExpression;
import net.sourceforge.pmd.lang.java.ast.ASTExpressionStatement;
import net.sourceforge.pmd.lang.java.ast.ASTFieldAccess;
import net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration;
import net.sourceforge.pmd.lang.java.ast.ASTReturnStatement;
import net.sourceforge.pmd.lang.java.ast.ASTThisExpression;
import net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration;
import net.sourceforge.pmd.lang.java.ast.ASTVariableAccess;
import net.sourceforge.pmd.lang.java.ast.Annotatable;
import net.sourceforge.pmd.lang.java.ast.JModifier;
import net.sourceforge.pmd.lang.java.rule.AbstractJavaRule;
import net.sourceforge.pmd.lang.java.symbols.JFieldSymbol;
import net.sourceforge.pmd.lang.java.types.TypeTestUtil;

/** Mechanical Lombok equivalence, deliberately independent of IOSP accessor neutrality. */
public final class LombokAccessorRule extends AbstractJavaRule {
  public LombokAccessorRule() {
    setName("LombokSimpleAccessor");
    setLanguage(JavaLanguageModule.getInstance());
    setMessage("Simple accessors must be generated by Lombok");
  }

  @Override
  public Object visit(ASTMethodDeclaration method, Object context) {
    var owner = method.ancestors(ASTTypeDeclaration.class).first();
    if (owner != null && owner.isRegularClass() && eligible(method)) {
      var replacement = getter(method);
      if (replacement.isEmpty()) {
        replacement = setter(method);
      }
      if (!replacement.isEmpty()) {
        var message =
            "LOMBOK_SIMPLE_ACCESSOR: "
                + owner.getBinaryName()
                + "#"
                + method.getName()
                + " is mechanical; use "
                + replacement;
        asCtx(context).addViolationNoSuppress(method, method.getAstInfo(), "{0}", message);
      }
    }
    return super.visit(method, context);
  }

  private static boolean eligible(ASTMethodDeclaration method) {
    return method.getBody() != null
        && !method.isStatic()
        && !method.isVarargs()
        && !method.hasModifiers(JModifier.SYNCHRONIZED)
        && !method.isAnyAnnotationPresent(Set.of("lombok.Synchronized", "lombok.Locked"))
        && method.getThrowsList() == null
        && method.getSymbol().getTypeParameters().isEmpty();
  }

  private static String getter(ASTMethodDeclaration method) {
    if (method.getArity() != 0
        || method.isVoid()
        || method.getBody().getNumChildren() != 1
        || !(method.getBody().getChild(0) instanceof ASTReturnStatement returned)) {
      return "";
    }
    var field = ownField(returned.getExpr(), method);
    if (field == null
        || !returned.getExpr().getTypeMirror().equals(method.getResultTypeNode().getTypeMirror())) {
      return "";
    }
    return replacement(method, field, true, false);
  }

  private static String setter(ASTMethodDeclaration method) {
    var body = method.getBody();
    if (method.getArity() != 1
        || body.getNumChildren() < 1
        || !(body.getChild(0) instanceof ASTExpressionStatement statement)
        || !(statement.getChild(0) instanceof ASTAssignmentExpression assignment)
        || assignment.isCompound()
        || !(assignment.getRightOperand() instanceof ASTVariableAccess value)) {
      return "";
    }
    var field = ownField(assignment.getLeftOperand(), method);
    var parameter = method.getFormalParameters().get(0).getVarId();
    if (field == null
        || field.isFinal()
        || !parameter.getSymbol().equals(value.getReferencedSym())
        || !assignment.getLeftOperand().getTypeMirror().equals(parameter.getTypeMirror())) {
      return "";
    }
    var chained =
        body.getNumChildren() == 2
            && body.getChild(1) instanceof ASTReturnStatement returned
            && returned.getExpr() instanceof ASTThisExpression self
            && self.getQualifier() == null
            && self.getTypeMirror().equals(method.getResultTypeNode().getTypeMirror());
    if (!(method.isVoid() && body.getNumChildren() == 1) && !chained) {
      return "";
    }
    return replacement(method, field, false, chained);
  }

  private static JFieldSymbol ownField(ASTExpression expression, ASTMethodDeclaration method) {
    if (!(expression instanceof ASTNamedReferenceExpr reference)
        || !(reference.getReferencedSym() instanceof JFieldSymbol field)
        || field.isStatic()
        || !field.getEnclosingClass().equals(method.getSymbol().getEnclosingClass())) {
      return null;
    }
    if (expression instanceof ASTFieldAccess access
        && (!(access.getQualifier() instanceof ASTThisExpression self)
            || self.getQualifier() != null)) {
      return null;
    }
    return field;
  }

  private static String replacement(
      ASTMethodDeclaration method, JFieldSymbol field, boolean getter, boolean chained) {
    var property = propertyName(field);
    if (property.isEmpty()) {
      return "";
    }
    var isBoolean = TypeTestUtil.isExactlyA(boolean.class, field.tryGetNode().getTypeMirror());
    var suffix = capitalize(property);
    var bean = (getter && isBoolean ? "is" : getter ? "get" : "set") + suffix;
    if (isBoolean
        && property.startsWith("is")
        && property.length() > 2
        && !Character.isLowerCase(property.charAt(2))) {
      bean = getter ? property : "set" + property.substring(2);
    }
    var fluent = method.getName().equals(property);
    if (!fluent && !method.getName().equals(bean)) {
      return "";
    }
    var options = new ArrayList<String>();
    options.add("fluent = " + fluent);
    if (!getter) {
      options.add("chain = " + chained);
    }
    if (method.isFinal()) {
      options.add("makeFinal = true");
    }
    return (getter ? "@Getter" : "@Setter")
        + "(AccessLevel."
        + visibility(method)
        + ")"
        + " with @Accessors("
        + String.join(", ", options)
        + "), preserving field prefixes";
  }

  private static String visibility(ASTMethodDeclaration method) {
    for (var modifier : List.of(JModifier.PUBLIC, JModifier.PROTECTED, JModifier.PRIVATE)) {
      if (method.hasModifiers(modifier)) {
        return modifier.name();
      }
    }
    return "PACKAGE";
  }

  private static String propertyName(JFieldSymbol field) {
    var declaration = field.tryGetNode();
    if (declaration == null) {
      return "";
    }
    // Lombok's prefix setting cascades from the field through enclosing types.
    for (var scope : declaration.ancestors()) {
      if (scope instanceof Annotatable annotated) {
        var accessors = annotated.getAnnotation("lombok.experimental.Accessors");
        if (accessors != null && accessors.getAttribute("prefix") != null) {
          if (accessors.getFlatValue("prefix").isEmpty()) {
            return field.getSimpleName();
          }
          for (var prefix : accessors.getFlatValue("prefix")) {
            if (prefix.getConstValue() instanceof String text) {
              var name = stripPrefix(field.getSimpleName(), text);
              if (!name.isEmpty()) {
                return name;
              }
            }
          }
          return "";
        }
      }
    }
    return field.getSimpleName();
  }

  private static String stripPrefix(String field, String prefix) {
    if (prefix.isEmpty()) {
      return field;
    }
    if (!field.startsWith(prefix) || field.length() <= prefix.length()) {
      return "";
    }
    var following = field.charAt(prefix.length());
    if (Character.isLetter(prefix.charAt(prefix.length() - 1))
        && Character.isLowerCase(following)) {
      return "";
    }
    return Character.toLowerCase(following) + field.substring(prefix.length() + 1);
  }

  private static String capitalize(String name) {
    return Character.toTitleCase(name.charAt(0)) + name.substring(1);
  }
}
